# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
- script: |
    pwd
    npm i --only=production
    mkdir _output
    cp -t _output -r bin routes node_modules app.js package.json package-lock.json
    ls -l
  displayName: 'npm cli'

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: 'Docker HUB'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker HUB'
    repository: 'damwar/catalog-api'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
