# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm i --only=production
    mkdir _output
    cp -t _output -r bin routes node_modules app.js package.json package-lock.json
    npm i
    npm run test
  displayName: 'npm cli'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '$(Pipeline.Workspace)/test_results'
    searchFolder: '$(Pipeline.Workspace)'
    testRunTitle: 'Tests'
    
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/_output'
    artifact: 'production-artifact'
    publishLocation: 'pipeline'