name: Docker Image CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Install production dependencies
          run: npm i --only=production
        - name: Copy production files to a separate folder
          run:  |
                mkdir _output
                cp -t _output -r bin routes node_modules app.js package.json package-lock.json
                
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v3.1.1
          with:
            push: true
            tags: damwar/catalog-api:latest
