name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install production dependencies
    - run: npm i --only=production
    - name: Copy production files to a separate folder
    - run:  |
            mkdir _output
            cp -t _output -r bin routes node_modules app.js package.json package-lock.json
    
    - name: Install dev dependencies
    - run: npm i
    - name: Test
    - run: npm run test
    
    - name: Export test resuts
      uses: actions/upload-artifact@v3
      with:
            name: test-results
            path: test_results/
    - name: Export project
      uses: actions/upload-artifact@v3
      with:
            name: production-artifact
            path: _output/
